<?php

/**
 * @file
 * Install, update and uninstall functions for the OneLogin SAML module.
 */

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function onelogin_saml_install() {
  // Users shouldn't be able to change thier usernames
  user_role_revoke_permissions(RoleInterface::AUTHENTICATED_ID, array('change own username'));
}

/**
 * Implements hook_uninstall().
 */
function onelogin_saml_uninstall() {
}
